title: "Capacity Assessment of Latin American and Caribbean Partners: A Symposium about Open-Access, Technological Needs, and Institutional Sustainability"
url: http://LacClirSymposium2020.github.io

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

# navigation:
#   - title: About
#     url: /index.html
#   - title: Speakers
#     url: /speakers
#   - title: The Symposium
#     url: /symposium

name: 
  en: Multilingual DH
  de: Mehrsprachige Digital Humanities 
  it: Digital Humanities Multilingue
  eo: Multlingvaj Teksta Analizo 
description: 
  en: Resources for doing digital humanities in many languages
  de: Ressourcen für die Textanalyse in vielen Sprachen
  it: Risorse per l'analisi del testo in molte lingue
  eo: Metodoj por analizo de tekstoj en multaj lingvoj
footer:
  en: An open-source project.
  de: Ein open-source Projekt. 
  it: Un progetto open-source.
  eo: Malferma projecto
exclude: [README.md]
permalink: pretty
repository: mrzool/polyglot-jekyll
base-url: ""

#social:
#  github: brianmaierjr
#  twitter: brianmaierjr
#  facebook: brianmaierjr
#  email: brimaidesigns@gmail.com

#google_analytics: "UA-58263416-1"
